version: "3.5"

services:
  postgres:
    container_name: naksha_postgres
    build:
      context: ./database
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: naksha_pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    container_name: naksha_backend
    build:
      context: ./backend
    env_file: .env
    volumes:
      - backend_war:/var/lib/postgresql/data
      - backend_apps:/apps
    expose:
      - "8080"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: naksha_frontend
    build:
      context: ./frontend
    env_file: .env
    ports:
      - "80:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  backend_war:
  backend_apps:
